import math

# UI const
POINT_RADIUS = 20
CANVAS_WIDTH = 1000
CANVAS_HEIGHT = 1000
ROBOT_WIDTH = 20
ROBOT_HEIGHT = 20
X_AXES_WIDTH = 4
X_AXES_LENGTH = 200
Y_AXES_WIDTH = 4
Y_AXES_LENGTH = 200

# Robot const
TURN_RADIUS = 3
VELOCITY = 1.5
MESSAGE_FREQUENCY = 0.1
DISTANCE_1_MESSAGE = VELOCITY * MESSAGE_FREQUENCY

_CIRCUMFERENCE = 2*math.pi*TURN_RADIUS
_TIME_CIRCUMFERENCE = _CIRCUMFERENCE / VELOCITY
_NUMBER_OF_MESSAGES_1_CIRCUMFERENCE = math.ceil(_TIME_CIRCUMFERENCE / MESSAGE_FREQUENCY)
ANGLE_AFTER_1_MESSAGE = (2*math.pi) / _NUMBER_OF_MESSAGES_1_CIRCUMFERENCE
ANGLE_ERROR = 2
# dy dx wzgledem lokalnej
DX_AFTER_1_MESSAGE = TURN_RADIUS * 2 * math.sin(ANGLE_AFTER_1_MESSAGE / 2) * math.cos((math.pi - ANGLE_AFTER_1_MESSAGE) / 2)
DY_AFTER_1_MESSAGE = TURN_RADIUS * 2 * math.sin(ANGLE_AFTER_1_MESSAGE / 2) * math.sin((math.pi - ANGLE_AFTER_1_MESSAGE) / 2)

# Resolution
RESOLUTION_X = math.ceil(CANVAS_WIDTH * DISTANCE_1_MESSAGE)
RESOLUTION_Y = math.ceil(CANVAS_HEIGHT * DISTANCE_1_MESSAGE)

# Constants for command meanings
GO_FORWARD=1
GO_LEFT=2
GO_RIGHT=3
GO_BACKWARD=4
STOP=0


